Models/CompletedPrompts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CommAcc5.Models
{
    public class CompletedPrompts
    {
        [Key]
        public int completed_id { get; set; }
        //Foreign Key from Prompts Model
        public int p_id { get; set; }
        //The prompt to hold
        public Prompts prompts { get; set; }

        public string book_name { get; set; }

        public string author_name { get; set; }

        public int rating { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CommAcc5.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Prompts.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CommAcc5.Models
{
    public class Prompts
    {

        [Key]
        public int p_id { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        public string prompt { get; set; }
    }
}

Controllers/CompletedPromptsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommAcc5.Data;
using CommAcc5.Models;
using Microsoft.AspNetCore.Authorization;

namespace CommAcc5.Controllers
{
    public class CompletedPromptsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CompletedPromptsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: CompletedPrompts
        public async Task<IActionResult> Index()
        {
            return View(await _context.CompletedPrompts.ToListAsync());
        }

        // GET: CompletedPrompts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var completedPrompts = await _context.CompletedPrompts
                .FirstOrDefaultAsync(m => m.completed_id == id);
            if (completedPrompts == null)
            {
                return NotFound();
            }

            return View(completedPrompts);
        }

        // GET: CompletedPrompts/Create
        [Authorize]
        public IActionResult Create()
        {
            //Getting Data from DB
            List<Prompts> promptList = new List<Prompts>();
            ViewData["p_id"] = new SelectList(_context.Prompts, "p_id", "prompt");

            return View();
        }

        // POST: CompletedPrompts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("completed_id,p_id,book_name,author_name,rating")] CompletedPrompts completedPrompts)
        {
            if (ModelState.IsValid)
            {
                _context.Add(completedPrompts);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(completedPrompts);
        }

        // GET: CompletedPrompts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var completedPrompts = await _context.CompletedPrompts.FindAsync(id);
            if (completedPrompts == null)
            {
                return NotFound();
            }
            return View(completedPrompts);
        }

        // POST: CompletedPrompts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("completed_id,p_id,book_name,author_name,rating")] CompletedPrompts completedPrompts)
        {
            if (id != completedPrompts.completed_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(completedPrompts);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompletedPromptsExists(completedPrompts.completed_id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(completedPrompts);
        }

        // GET: CompletedPrompts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var completedPrompts = await _context.CompletedPrompts
                .FirstOrDefaultAsync(m => m.completed_id == id);
            if (completedPrompts == null)
            {
                return NotFound();
            }

            return View(completedPrompts);
        }

        // POST: CompletedPrompts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var completedPrompts = await _context.CompletedPrompts.FindAsync(id);
            _context.CompletedPrompts.Remove(completedPrompts);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompletedPromptsExists(int id)
        {
            return _context.CompletedPrompts.Any(e => e.completed_id == id);
        }

        public async Task<IActionResult> Searching()
        {
            return View();
        }

        public async Task<IActionResult> ShowSearchResults(string SearchCompletedPrompts)
        {
            return View("Index", await _context.CompletedPrompts.Where(s => s.author_name.Contains(SearchCompletedPrompts)).ToListAsync());
        }
    }
}

Controllers/HomeController.cs
using CommAcc5.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CommAcc5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/CompletedPrompts/Create.cshtml
@model CommAcc5.Models.CompletedPrompts

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Complete A Prompt</h4>
<hr />
<div class="row bg-dark text-light">
    <div class="col-md-4">
        <form class="bg-dark text-light" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="p_id" class="control-label">Select a Prompt</label>
                <select asp-for="p_id" class="form-control  bg-dark text-light border border-secondary" asp-items="@ViewBag.p_id"></select>
                <span asp-validation-for="p_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="book_name" class="control-label">Book Title</label>
                <input asp-for="book_name" class="form-control  bg-dark text-light border border-secondary" />
                <span asp-validation-for="book_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="author_name" class="control-label">Authors Name</label>
                <input asp-for="author_name" class="form-control  bg-dark text-light border border-secondary" />
                <span asp-validation-for="author_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rating" class="control-label">Rating</label>
                <select asp-for="rating" class="form-control  bg-dark text-light border border-secondary">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                </select>
                <span asp-validation-for="rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="button" class="btn btn-outline-secondary text-light btn-block"> <a class="text-light" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompletedPrompts/Delete.cshtml
@model CommAcc5.Models.CompletedPrompts

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Delete a Complete Prompt</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Prompt ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.p_id)
        </dd>
        <dt class="col-sm-2">
            Book Title
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.book_name)
        </dd>
        <dt class="col-sm-2">
            Author Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.author_name)
        </dd>
        <dt class="col-sm-2">
            Rating
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.rating)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="completed_id" />
        <input type="submit" value="Delete" class="btn btn-block btn-danger" /> <hr />
        <button type="button" class="btn btn-outline-secondary text-light btn-block">
            <a class="text-light" asp-action="Index">Back to List</a>
        </button>
    </form>
</div>

Views/CompletedPrompts/Details.cshtml
@model CommAcc5.Models.CompletedPrompts

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Details of a Completed Prompt</h4>
    <hr />
    <button type="button" class="btn btn-outline-info text-light btn-block">
        <a class="text-light" asp-action="Edit" asp-route-id="@Model.completed_id">Edit</a>
    </button>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Prompt ID
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.p_id)
        </dd>
        <dt class="col-sm-2">
            Book Title
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.book_name)
        </dd>
        <dt class="col-sm-2">
            Authors Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.author_name)
        </dd>
        <dt class="col-sm-2">
            Rating
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.rating)
        </dd>
    </dl>
</div>
<div>

    <button type="button" class="btn btn-outline-secondary text-light btn-block"> <a class="text-light" asp-action="Index">Back to List</a></button>
</div>

Views/CompletedPrompts/Edit.cshtml
@model CommAcc5.Models.CompletedPrompts

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Edit an Completed Prompt</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="completed_id" />
            <div class="form-group">
                <label asp-for="p_id" class="control-label">Prompt ID</label>
                <input asp-for="p_id" class="form-control bg-dark text-light border border-secondary" />
                <span asp-validation-for="p_id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="book_name" class="control-label">Book Title</label>
                <input asp-for="book_name" class="form-control bg-dark text-light border border-secondary" />
                <span asp-validation-for="book_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="author_name" class="control-label">Author's Name</label>
                <input asp-for="author_name" class="form-control bg-dark text-light border border-secondary" />
                <span asp-validation-for="author_name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="rating" class="control-label">Rating</label>
                <select asp-for="rating" class="form-control  bg-dark text-light border border-secondary">
                    <option>1</option>
                    <option>2</option>
                    <option>3</option>
                    <option>4</option>
                    <option>5</option>
                    <option>6</option>
                    <option>7</option>
                    <option>8</option>
                    <option>9</option>
                    <option>10</option>
                </select>
                <span asp-validation-for="rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary btn-block" />
            </div>
        </form>
    </div>
</div>

<div>
    <button type="button" class="btn btn-outline-secondary text-light btn-block"> <a class="text-light" asp-action="Index">Back to List</a></button>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/CompletedPrompts/Index.cshtml
@model IEnumerable<CommAcc5.Models.CompletedPrompts>

@{
    ViewData["Title"] = "Index";
}

<h1>List of Completed Prompts!</h1>

<p>
    <button type="button" class="btn btn-outline-primary text-light btn-block"><a class="text-light" asp-action="Create">Create New</a></button>
</p>
<table class="table bg-dark text-light">
    <thead>
        <tr>
            <th>
                Prompt ID
            </th>
            <th>
                Book Title
            </th>
            <th>
                Author
            </th>
            <th>
                Rating
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td width="10%">
                    @Html.DisplayFor(modelItem => item.p_id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.book_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.author_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.rating)
                </td>
                <td>
                    <button type="button" class="btn btn-outline-info text-light btn-sm"><a asp-action="Edit" asp-route-id="@item.completed_id">Edit</a></button> |
                    <button type="button" class="btn btn-outline-info text-light btn-sm"><a asp-action="Details" asp-route-id="@item.completed_id">Details</a></button> |
                    <button type="button" class="btn btn-outline-danger text-light btn-sm"><a asp-action="Delete" asp-route-id="@item.completed_id">Delete</a></button>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/CompletedPrompts/Searching.cshtml
@model CommAcc5.Models.CompletedPrompts

<h4>Search Completed Prompts by Author</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label name="SearchCompletedPrompts" class="control-label">Search By Author's Name</label>
                <input name="SearchCompletedPrompts" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center bg-dark text-light">
    <h1 class="display-4">Welcome to my Reading Challenge!</h1>
    <p>This is where I'll be keeping track of my reading challenges for the year of 2020!</p><br />
    <br />
    <p>For more information on where I got my prompts visit: <a href="https://www.popsugar.com/entertainment/photo-gallery/46857621/image/46908485/2020-POPSUGAR-Reading-Challenge">PopSugar!</a></p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-dark text-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/css/Resources/finnlogo.ico" height="100" width="100" alt="Logo" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item list-group-horizontal">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item list-group-horizontal">
                            <a class="nav-link text-light" asp-area="" asp-controller="CompletedPrompts" asp-action="Create">Complete a Prompt</a>
                        </li>
                        <li class="nav-item list-group-horizontal">
                            <a class="nav-link text-light" asp-area="" asp-controller="CompletedPrompts" asp-action="Index">View Completed</a>
                        </li>
                        <li class="nav-item list-group-horizontal">
                            <a class="nav-link text-light" asp-area="" asp-controller="CompletedPrompts" asp-action="Searching">Search By Author</a>
                        </li>
                        <li class="nav-item list-group-horizontal">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-dark text-light">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted  text-light bg-dark">
        <div class="container">
            &copy; 2020 - CommAcc5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>